/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX_1_aliases.h"
#include "RX_1.h"
#include "TX_1_aliases.h"
#include "TX_1.h"
#include "CAN_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "UART_1.h"
#include "AMux_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "ADC_DelSig_1.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Pin_4_aliases.h"
#include "Pin_4.h"
#include "Pin_5_aliases.h"
#include "Pin_5.h"
#include "Pin_6_aliases.h"
#include "Pin_6.h"
#include "UART_1_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

